---
abstract: 'Google Web Fonts from your terminal'
author:
  - 'Mark Allen <mrallen1@yahoo.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-gfonts
requires:
  IO::Socket::SSL: 1.88
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-gfonts
  homepage: https://metacpan.org/dist/App-gfonts
  repository: git://github.com/mrallen1/App-gfonts.git
version: 0.01
